use Salesforce

-- list table.column metadata attributes in ArcBest data dictionary worksheet order
select TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX, NUMERIC_SCALE, DATETIME_PRECISION
from Salesforce.INFORMATION_SCHEMA.COLUMNS
--where TABLE_NAME = N'account_address_seed' AND TABLE_SCHEMA = N'osc'
where CHARINDEX('SEED',TABLE_NAME) > 0 AND TABLE_SCHEMA = N'osc'
order by TABLE_NAME, ORDINAL_POSITION


select TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX, NUMERIC_SCALE, DATETIME_PRECISION
from Salesforce.INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = N'OPPORTUNITY_SEED' AND TABLE_SCHEMA = N'osc'
--where TABLE_SCHEMA = N'osc'
order by TABLE_NAME, ORDINAL_POSITION

select TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX, NUMERIC_SCALE, DATETIME_PRECISION
from Salesforce.INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = N'ACCOUNT_SEED' AND TABLE_SCHEMA = N'osc'
--where TABLE_SCHEMA = N'osc'
order by TABLE_NAME, ORDINAL_POSITION
